defaults:
  - dataset: defaults
  - loader: defaults
  - hydra: defaults
  - _self_

hydra:
  run:
    dir: ./outputs/saliency_maps/${model_name}/${now:%Y-%m-%d}-${dataset.name}/${now:%H-%M-%S}-${vis}
model_name: simclr
model_checkpoint: ""
loader.batch_size: 1
vis: saliency_maps_v1
just_backbone: False