# bbox extraction:
num_erode: 2
num_dilate: 5
skip_bg_index: True
downsample_factor: null
# bbox features
C_pos: 0.0
C_mask: 0.0
# bbox clustering:
num_clusters: 20
seed: 1
pca_dim: 0
clustering: kmeans
should_use_siamese: null
should_use_ae: null
is_sparse_graph: null
spectral_n_nbg: null
feat_comb_method: sum