mode: precomputed
features: "/outputs/oleksandra_tmenova/SegmPipelineUS/experiments/110512/liver2_mini/features/dino_vits8"
eig: "/outputs/oleksandra_tmenova/SegmPipelineUS/experiments/110512/liver2_mini/eig/laplacian"
multi_region_segmentation:  "/outputs/oleksandra_tmenova/SegmPipelineUS/experiments/110512/liver2_mini/multi_region_segmentation/laplacian"
bboxes:  "/outputs/oleksandra_tmenova/SegmPipelineUS/experiments/110512/liver2_mini/multi_region_bboxes/laplacian/bboxes.pth"
bbox_features: "/outputs/oleksandra_tmenova/SegmPipelineUS/experiments/110687/liver2_mini/multi_region_bboxes/laplacian/bbox_features.pth"
bbox_clusters: ""
segmaps: ""
crf_segmaps: ""