name: aff_sweep
seg_for_eval: multi_region
method: grid
count: null
config:
  segments_num:
    values: [8]
  clusters_num:
    values: [6]
  multi_region_segmentation:
    parameters:
      non_adaptive_num_segments:
        values: [8]
  spectral_clustering:
    parameters:
      K:
        values: [8]
      C_dino:
        values: [1.0]
      C_ssd_knn:
        values: [0.0, 0.5, 1.0]
      max_knn_neigbors:
        values: [80]
      C_var_knn:
        values: [0.0]
      C_pos_knn:
        values: [0.0, 0.5, 1.0]
      C_ssd:
        values: [0.0, 0.5, 1.0]
      C_ncc:
        values: [0.0]
      C_lncc:
        values: [0.0]
      C_ssim:
        values: [0.0]
      C_mi:
        values: [0.0, 0.5, 1.0]
      C_sam:
        values: [0.0]
      patch_size:
        values: [8]
      aff_sigma:
        values: [6.5]
        # values: [5.0, 6.0, 6.5, 7.0, 7.5, 8.0]
      distance_weight1:
        values: [2.0]
      distance_weight2:
        values: [0.1]