name: aff_all_sweep
seg_for_eval: crf_segmaps
method: bayes
count: 20
config:
  spectral_clustering:
    parameters:
      C_dino:
        values: [0.0, 1.0]
      C_ssd_knn:
        values: [0.0, 1.0]
      max_knn_neigbors:
        max: 80
        min: 8
      C_var_knn:
        values: [0.0, 1.0]
      C_pos_knn:
        values: [0.0, 1.0]
      C_ssd:
        values: [0.0, 1.0]
      C_ncc:
        values: [0.0, 1.0]
      C_lncc:
        values: [0.0, 1.0]
      C_ssim:
        values: [0.0, 1.0]
      C_mi:
        values: [0.0, 1.0]
      C_sam:
        values: [0.0, 1.0]
      patch_size:
        values: [16, 8]
      aff_sigma:
        max: 10.0
        min: 0.001
