name: crf_sweep
seg_for_eval: crf_segmaps
method: bayes
count: 20
config:
  crf:
    parameters:
      w1:
        max: 20.0
        min: 4.0
      alpha:
        max: 100.0
        min: 30.0
      beta:
        max: 24.0
        min: 2.0
      w2:
        max: 16.0
        min: 1.0
      gamma:
        max: 6.0
        min: 1.0
      it:
        max: 15.0
        min: 5.0
