name: models
seg_for_eval: ['segmaps', 'multi_region']
method: grid
count: 
config:
  vis:
    parameters:
      dino_attn_maps:
        values: [True]
      eigen:
        values: [True]
  model:
    parameters:
      name:
        values:
          - dino_vits8
          - dinov2_vits14
          - dino_vitb8
          - dinov2_vitb14
          - dinov2_vits14_reg
          - dinov2_vitb14_reg
      checkpoint:
        values: [""]  # Add your list of checkpoint paths here
        # "/home/guests/oleksandra_tmenova/test/project/thesis-codebase/self-training/outputs/models/2023-11-11-train_dinoLightningModule/21-17-15-us_mixed_train/epoch=28-step=2059-train_loss=0.34-val_loss=0.28.ckpt"