name: preprocess_sweep
seg_for_eval: multi_region
method: grid
count: 96
config:
  norm:
    values: ["none", 'custom', 'imagenet', 'custom_global']
  preprocessed_data:
    values: ['derained', 'mixed', null]
  inv:
    values: [True, False]
  hist_eq:
    values: [True, False]
  gauss_blur:
    values: [True, False]
  pipeline_steps:
    parameters:
      bbox:
        values: [False]
      bbox_features:
        values: [False]
      clusters:
        values: [False]
      sem_segm:
        values: [False]
      crf_segm:
        values: [False]
      crf_multi_region:
        values: [False]
  segments_num:
    values: [28]
  clusters_num:
    values: [7]