name: segments_clusters_thyroid_sweep
seg_for_eval: crf_segmaps
method: bayes
count: 20
config:
  segments_num:
    max: 30
    min: 10
  clusters_num:
    values: [7]
  # or
  # clusters_num:
  #   values: [6, 7, 8, 9, 10, 11, 12]