name: segments_clusters_carotids
seg_for_eval: ['segmaps']
method: bayes
count: 20
config:
  segments_num:
    values: [7, 10, 15, 16, 17, 18, 19, 20, 21, 22]
  clusters_num:
    values: [6, 7, 8, 9, 10, 11, 12, 13, 14, 15]