name: segments_clusters_liver_sweep
seg_for_eval: crf_segmaps
method: bayes
count: 20
config:
  segments_num:
    max: 30
    min: 8
  clusters_num:
    values: [6]
  # or
  # clusters_num:
  #   values: [5, 6, 7, 8, 9, 10]
