name: spectral_net_vs_kmeans
seg_for_eval: crf_segmaps
method: grid
count: null
config:
  bbox:
    parameters:
      clustering:
        values: ['spectral_net', 'kmeans']
      should_use_siamese:
        values: [True]
      should_use_ae:
        values: [True]
      is_sparse_graph:
        values: [False]
      spectral_n_nbg:
        values: [48]
  segments_num:
    values: [6, 8, 14]
  clusters_num:
    values: [6]
