name: carotid_mixed_val_mini
dataset_root: CAROTID_MIXED/val_mini
input_size: 256
images_root: images
list: lists/images.txt
gt_dir: labels
pred_dir: ""
n_classes: 2
n_clusters:
features_dir:
preprocessed_dir: preprocessed