name: thyroid_single_side_test
dataset_root: THYROID_SINGLE_SIDE/test
input_size: 512
images_root: images
list: lists/images.txt
gt_dir: labels
pred_dir: ""
n_classes: 2
n_clusters:
features_dir: features/dino_vits8
