which_matrix: laplacian
which_color_matrix: knn
which_features: k
normalize: True
threshold_at_zero: True
lapnorm: True
K: 20
image_downsample_factor: null
image_color_lambda: 0.0
multiprocessing: 0
image_ssd_beta: 0.0
