which_matrix: laplacian
which_color_matrix: knn
which_features: k
normalize: True
threshold_at_zero: True
lapnorm: True
K: 20
image_downsample_factor: null
image_color_lambda: 0.0
multiprocessing: 0
C_ssd_knn: 0.0
C_dino: 1.0
max_knn_neigbors: 80
C_var_knn:  0.0
C_pos_knn:  0.0
C_ssd:  0.0
C_ncc:  0.0
C_lncc:  0.0
C_ssim:  0.0
C_mi:  0.0
C_sam:  0.0
patch_size: 8
aff_sigma:  0.01
distance_weight1:  null
distance_weight2:  null
