name: aff
seg_for_eval: ['crf_multi_region']
method: grid
count: 
simple: True
sweep_id: null
config:
    # generic
    segments_num: [15]
    clusters_num: [15]

    # affinities
    spectral_clustering:
        C_dino: [1.0]
        C_ssd: [0.0, 1.0]
        C_mi: [0.0, 1.0]
        C_pos: [0.0]

    # postprocessing (CRF)
    crf:
        w1: [15]
        alpha: [7]
        beta: [10]
        w2: [5]
        gamma: [5]
        it: [10]