name: carotid_mutinfo
path: ../data/carotid_mutinfo/train
val_path: ../data/carotid_mutinfo/val
rel_train_path: carotid_mutinfo/train
rel_val_path: carotid_mutinfo/val
input_size: 256
images_root: train