version: 1
kind: group
framework: pytorch
tags:
  - dinov1_vits8
  - freezing half of the layers
  - group_exp
build:
  image: pytorchlightning/pytorch_lightning:base-xla-py3.7-torch1.12
  build_steps:
    - pip install -r requirements.txt
    - pip install markupsafe==2.0.1 --force
    - pip3 install torch_xla[tpuvm]
    - pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117

environment:
  resources:
    cpu:
      requests: 4
      limits: 12
    memory:
      requests: 24576
      limits: 64000
    gpu:
      requests: 1
      limits: 1
  node_selector:
    gpuMemory: "32"
  

params:
  batch_size: 48
  exp_name: train_dinoLightningModule
  backbone: dino_vits8
  epochs: 50
  loader_num_workers: 8
  dataset_input_size: 256
  train_lr: 1e-5
  train_weight_decay: 1e-5

hptuning:
  concurrency: 1
  matrix:
    pretrained_weights:
      values: [True]
    dataset:
      values: [carotid_mutinfo]
    fraction_layers_to_freeze:
      values: [0.0, 0.5]
    loader:
      values: [defaults,patch64]
    

run:
  cmd: python -m tasks.train \
      wandb.setup.project=SSL-fine-tuning \
      wandb=server \
      dataset={{ dataset }} \
      experiment.name={{ exp_name }} \
      train.backbone={{ backbone }} \
      train.epochs={{ epochs }} \
      train.pretrained_weights={{ pretrained_weights }} \
      loader.batch_size={{ batch_size }} \
      loader.num_workers={{ loader_num_workers }}  \
      dataset.input_size={{ dataset_input_size }} \
      loader={{ loader }} \
      train.lr={{ train_lr }} \
      train.weight_decay={{ train_weight_decay }} \
      train.fraction_layers_to_freeze={{ fraction_layers_to_freeze }}

